/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AddPO extends javax.swing.JFrame {

    /**
     * Creates new form AddPO
     */
    Connection conn=null;
    
    public AddPO() {
        super("AddPO");
        initComponents();
        conn=databaseconnection.connection();
    }
    
    public void reset()
    {
        OrderID.setText("");
        Date.setText("");
        Quantity.setText("");
        CostValue.setText("");
        SaleValue.setText("");
        SupID.setText("");
        AppBy.setText("");
        AppDate.setText("");
        Status.setSelectedItem("");
        prod_id.setText("");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        supID = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        sale = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        appBy = new javax.swing.JTextField();
        appDate = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        CostValue = new javax.swing.JTextField();
        AppDate = new javax.swing.JTextField();
        SaleValue = new javax.swing.JTextField();
        AppBy = new javax.swing.JTextField();
        orderID = new javax.swing.JTextField();
        OrderID = new javax.swing.JTextField();
        SupID = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        appDate1 = new javax.swing.JTextField();
        prod_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supID.setBackground(new java.awt.Color(210, 227, 195));
        supID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        supID.setForeground(new java.awt.Color(0, 128, 108));
        supID.setText("SUPPLIER ID");
        supID.setBorder(null);
        jPanel1.add(supID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, 50));

        cost.setBackground(new java.awt.Color(210, 227, 195));
        cost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cost.setForeground(new java.awt.Color(0, 128, 108));
        cost.setText("COST VALUE");
        cost.setBorder(null);
        jPanel1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 50));

        sale.setBackground(new java.awt.Color(210, 227, 195));
        sale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sale.setForeground(new java.awt.Color(0, 128, 108));
        sale.setText("SALE VALUE");
        sale.setBorder(null);
        jPanel1.add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 180, 50));

        status.setBackground(new java.awt.Color(210, 227, 195));
        status.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(0, 128, 108));
        status.setText("STATUS");
        status.setBorder(null);
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, 50));

        appBy.setBackground(new java.awt.Color(210, 227, 195));
        appBy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appBy.setForeground(new java.awt.Color(0, 128, 108));
        appBy.setText("APPROVED BY");
        appBy.setBorder(null);
        jPanel1.add(appBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 180, 50));

        appDate.setBackground(new java.awt.Color(210, 227, 195));
        appDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appDate.setForeground(new java.awt.Color(0, 128, 108));
        appDate.setText("APPROVED DATE");
        appDate.setBorder(null);
        jPanel1.add(appDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 180, 50));

        save.setBackground(new java.awt.Color(0, 128, 108));
        save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setBorder(null);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 690, 180, 50));

        Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 370, 40));

        clear.setBackground(new java.awt.Color(0, 128, 108));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("BACK");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 180, 50));

        CostValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(CostValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 370, 40));

        AppDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(AppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 370, 40));

        SaleValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(SaleValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 370, 40));

        AppBy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(AppBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 370, 40));

        orderID.setBackground(new java.awt.Color(210, 227, 195));
        orderID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        orderID.setForeground(new java.awt.Color(0, 128, 108));
        orderID.setText("ORDER ID");
        orderID.setBorder(null);
        orderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDActionPerformed(evt);
            }
        });
        jPanel1.add(orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 180, 50));

        OrderID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 370, 40));

        SupID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SupID.setBorder(null);
        jPanel1.add(SupID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 370, 40));

        date.setBackground(new java.awt.Color(210, 227, 195));
        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(0, 128, 108));
        date.setText("DATE");
        date.setBorder(null);
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 180, 50));

        Status.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Complete", "Cancelled" }));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 370, 40));

        quantity.setBackground(new java.awt.Color(210, 227, 195));
        quantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 128, 108));
        quantity.setText("QUANTITY");
        quantity.setBorder(null);
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, 50));

        Quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 370, 40));

        appDate1.setBackground(new java.awt.Color(210, 227, 195));
        appDate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appDate1.setForeground(new java.awt.Color(0, 128, 108));
        appDate1.setText("PRODUCT ID:");
        appDate1.setBorder(null);
        appDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appDate1ActionPerformed(evt);
            }
        });
        jPanel1.add(appDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 180, 50));

        prod_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(prod_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addPO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here
        setVisible(false);
        PurchaseOrder obj = new PurchaseOrder();
        obj.setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
         try {
        // Check if AppBy is a valid employee name
        String employeeCheckSql = "SELECT emp_id FROM Employee WHERE name = ?";
        try (PreparedStatement employeeCheckStmt = conn.prepareStatement(employeeCheckSql)) {
            employeeCheckStmt.setString(1, AppBy.getText());
            var resultSet = employeeCheckStmt.executeQuery();

            if (!resultSet.next()) {
                // Employee with the given name not found
                JOptionPane.showMessageDialog(this, "The name in Approved By is not a valid employee.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Valid employee name, get the emp_id
            String empId = resultSet.getString("emp_id");

            // Insert into PurchaseOrder
            String sql = "INSERT INTO PurchaseOrder VALUES(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);

            ptst.setString(1, OrderID.getText());
            ptst.setString(2, Date.getText());
            ptst.setString(3, SupID.getText());
            ptst.setString(4, empId); // Using emp_id from the Employee table
            ptst.setString(5, Quantity.getText());
            ptst.setString(6, CostValue.getText());
            ptst.setString(7, SaleValue.getText());
            ptst.setString(8, (String) Status.getSelectedItem());
            ptst.setString(9, AppDate.getText());
            ptst.setString(10, AppBy.getText());

            ptst.executeUpdate();

            // Include prod_id when inserting into ProdOrder
            if (prod_id.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter product ID.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String prodOrderSql = "INSERT INTO ProdOrder VALUES (?, ?)";
            PreparedStatement ptstProdOrder = conn.prepareStatement(prodOrderSql);
            ptstProdOrder.setString(1, OrderID.getText());
            ptstProdOrder.setString(2, prod_id.getText());
            ptstProdOrder.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Added Successfully");
            reset();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void orderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIDActionPerformed

    private void appDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appDate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AppBy;
    private javax.swing.JTextField AppDate;
    private javax.swing.JTextField CostValue;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField OrderID;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField SaleValue;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField SupID;
    private javax.swing.JTextField appBy;
    private javax.swing.JTextField appDate;
    private javax.swing.JTextField appDate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderID;
    private javax.swing.JTextField prod_id;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sale;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTextField supID;
    // End of variables declaration//GEN-END:variables
}
