
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    Connection conn = null;
    ResultSet rs;
    PreparedStatement pst;
    public void reset(){
            cust_id.setText("");
            cust_name.setText("");
            cust_phone.setText("");
            cust_type.setSelectedItem("Regular");
    }
    public customer() {
        super("Customer");
        initComponents();
        conn = databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cust_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cust_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cust_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cust_type = new javax.swing.JComboBox<>();
        p_history = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        search = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1122, 793));
        jPanel1.setPreferredSize(new java.awt.Dimension(1122, 793));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 108));
        jLabel5.setText("Customer ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        cust_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cust_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_idActionPerformed(evt);
            }
        });
        jPanel1.add(cust_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 108));
        jLabel6.setText("Customer Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        cust_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_nameActionPerformed(evt);
            }
        });
        jPanel1.add(cust_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 128, 108));
        jLabel7.setText("Customer Phone No.:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        cust_phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cust_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(cust_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 128, 108));
        jLabel8.setText("Customer Type:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        cust_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cust_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Employee", "Member" }));
        cust_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_typeActionPerformed(evt);
            }
        });
        jPanel1.add(cust_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        p_history.setBackground(new java.awt.Color(0, 128, 108));
        p_history.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p_history.setForeground(new java.awt.Color(255, 255, 255));
        p_history.setText("PURCHASE HISTORY");
        p_history.setBorder(null);
        p_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_historyActionPerformed(evt);
            }
        });
        jPanel1.add(p_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 170, 30));

        reset.setBackground(new java.awt.Color(0, 128, 108));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("CLEAR");
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 100, 30));

        add.setBackground(new java.awt.Color(0, 128, 108));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 100, 30));

        search.setBackground(new java.awt.Color(0, 128, 108));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 100, 30));

        delete.setBackground(new java.awt.Color(0, 128, 108));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 100, 30));

        update.setBackground(new java.awt.Color(0, 128, 108));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 100, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customerbg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 746));

        jMenuBar1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuBar1.setForeground(new java.awt.Color(0, 128, 108));

        jMenu1.setBackground(new java.awt.Color(210, 227, 195));
        jMenu1.setForeground(new java.awt.Color(0, 128, 108));
        jMenu1.setText("Home");

        jMenuItem1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuItem1.setForeground(new java.awt.Color(0, 128, 108));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeicon.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cust_nameActionPerformed

    private void cust_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_typeActionPerformed

    private void cust_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_idActionPerformed

    private void cust_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_phoneActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
    }//GEN-LAST:event_resetActionPerformed
    private boolean isCustomerIdExists(int cust_id) {

            try {
                pst = conn.prepareStatement("SELECT * FROM customer WHERE cust_id = ?");
                pst.setInt(1, cust_id);
                ResultSet rs = pst.executeQuery();
                return rs.next();  // Returns true if a record is found
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                return false;
            }
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(cust_id.getText());
        if (isCustomerIdExists(id)) {
            JOptionPane.showMessageDialog(this, "Customer with ID " + id + " already exists.", "Duplicate Entry", JOptionPane.ERROR_MESSAGE);
            
            cust_id.setText("");
            return;  // Exit the method to avoid further processing
        }
        try {
            pst = conn.prepareStatement("INSERT INTO customer(cust_id,cust_name,cust_phone,cust_type) VALUES (?,?,?,?)");
            pst.setInt(1, id);
            pst.setString(2,cust_name.getText());
            pst.setString(3,cust_phone.getText());
            pst.setString(4, cust_type.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data is sucessfully inserted.");
            reset();
            
            // Your existing code for resetting fields
            reset();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Customer ID. Please enter a valid integer.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            cust_id.setText("");
        }
              
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
        // TODO add your handling code here:
        String typeValue = (String) cust_type.getSelectedItem();
        // Check if values are not null before setting them in the prepared statement
        if (typeValue != null) {
            pst = conn.prepareStatement("UPDATE customer SET cust_name=?,cust_phone=?,cust_type=? WHERE cust_id=?");
            pst.setString(1, cust_name.getText());
            pst.setString(2, cust_phone.getText());
            pst.setString(3, typeValue);
            pst.setString(4, cust_id.getText());  // This should be the last parameter
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data is sucessfully updated.");
            reset();
        } else {
            // Handle the case where one or both values are null
            // You may want to provide default values or handle it according to your application logic
            // For example:
            JOptionPane.showMessageDialog(this, "Customer Type is null");
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         try{
            Statement stmt = conn.createStatement();
            String phone = cust_phone.getText();
            String sql = "SELECT * FROM customer WHERE cust_phone = '"+phone+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                cust_id.setText(rs.getString("cust_id"));
                cust_name.setText(rs.getString("cust_name"));
                cust_type.setSelectedItem(rs.getString("cust_type"));
            }
            else{
                JOptionPane.showMessageDialog(null,"Record Not Found");
            }

        }catch (SQLException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            pst=conn.prepareStatement("delete from customer where cust_phone=?");
            pst.setString(1,cust_phone.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data is sucessfully deleted.");
            reset();

        }catch (SQLException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void p_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_historyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        cust_phistory obj = new cust_phistory();
        obj.setVisible(true);
    }//GEN-LAST:event_p_historyActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //TODO add your handling code here:
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cust_id;
    private javax.swing.JTextField cust_name;
    private javax.swing.JTextField cust_phone;
    private javax.swing.JComboBox<String> cust_type;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton p_history;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
