/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class DeletePO extends javax.swing.JFrame {
    
    /**
     * Creates new form DeletePO
     */
    Connection conn=null;
    
    public DeletePO() {
        super("DeletePO");
        initComponents();
        conn=databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        orderID = new javax.swing.JTextField();
        OrderID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBackground(new java.awt.Color(0, 128, 108));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("BACK");
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 180, 50));

        delete.setBackground(new java.awt.Color(0, 128, 108));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 180, 50));

        orderID.setBackground(new java.awt.Color(210, 227, 195));
        orderID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        orderID.setForeground(new java.awt.Color(0, 128, 108));
        orderID.setText("ORDER ID");
        orderID.setBorder(null);
        jPanel1.add(orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 180, 50));

        OrderID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deletePO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        PurchaseOrder obj = new PurchaseOrder();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

         String dPO = OrderID.getText();
    try {
        if (OrderID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter order ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            // Delete from ProdOrder first
            String deleteProdOrderSQL = "DELETE FROM ProdOrder WHERE orderNo = ?";
            try (PreparedStatement ptstProdOrder = conn.prepareStatement(deleteProdOrderSQL)) {
                ptstProdOrder.setString(1, dPO);
                ptstProdOrder.executeUpdate();
            }

            // Then, delete from PurchaseOrder
            String deletePurchaseOrderSQL = "DELETE FROM PurchaseOrder WHERE orderNo = ?";
            try (PreparedStatement ptstPurchaseOrder = conn.prepareStatement(deletePurchaseOrderSQL)) {
                ptstPurchaseOrder.setString(1, dPO);
                ptstPurchaseOrder.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "The purchase order and related product orders have been deleted.");
            OrderID.setText("");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrderID;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderID;
    // End of variables declaration//GEN-END:variables
}
