/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.sql.Connection;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    Connection conn = null;
    ResultSet rs;
    PreparedStatement ptst;
    public Employee() {
        super("Employee");
        initComponents();
        
        // Create a custom header renderer
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(0, 128, 108));  // Set the background color
        headerRenderer.setForeground(new java.awt.Color(210, 227, 195));  // Set the text color

        // Apply the custom renderer to the JTableHeader
        jTable1.getTableHeader().setDefaultRenderer(headerRenderer);
        
        conn = databaseconnection.connection();
        viewEmployees();
    }
    
    public void reset()
    {
        id.setText("");
        name.setText("");
        dob.setText("");
        doj.setText("");
        type.setSelectedItem("");      
    }
    
    public void viewEmployees(){
        try{
        Statement stmt = conn.createStatement();
        String sql = "SELECT * FROM Employee";   //write whatever ur table name is
        ResultSet rs = stmt.executeQuery(sql);
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        home = new javax.swing.JButton();
        doj = new javax.swing.JTextField();
        empExperience = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        empType = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        empDOB = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        empID = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(210, 227, 195));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 108)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EMP ID", "NAME", "DATE OF BIRTH", "TYPE", "DATE OF JOINING"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 128, 108));
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 560, 270));

        home.setBackground(new java.awt.Color(0, 128, 108));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.setBorder(null);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 150, 50));

        doj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doj.setBorder(null);
        jPanel1.add(doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 370, 40));

        empExperience.setBackground(new java.awt.Color(210, 227, 195));
        empExperience.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empExperience.setForeground(new java.awt.Color(0, 128, 108));
        empExperience.setText("DATE OF JOINING");
        empExperience.setBorder(null);
        jPanel1.add(empExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 160, 50));

        type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Regular" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 370, 40));

        empType.setBackground(new java.awt.Color(210, 227, 195));
        empType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empType.setForeground(new java.awt.Color(0, 128, 108));
        empType.setText("TYPE");
        empType.setBorder(null);
        jPanel1.add(empType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 150, 50));

        dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dob.setBorder(null);
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 370, 40));

        empDOB.setBackground(new java.awt.Color(210, 227, 195));
        empDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empDOB.setForeground(new java.awt.Color(0, 128, 108));
        empDOB.setText("DATE OF BIRTH");
        empDOB.setBorder(null);
        jPanel1.add(empDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 150, 50));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 370, 40));

        empName.setBackground(new java.awt.Color(210, 227, 195));
        empName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empName.setForeground(new java.awt.Color(0, 128, 108));
        empName.setText("NAME");
        empName.setBorder(null);
        jPanel1.add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 150, 50));

        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setBorder(null);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 370, 40));

        empID.setBackground(new java.awt.Color(210, 227, 195));
        empID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        empID.setForeground(new java.awt.Color(0, 128, 108));
        empID.setText("EMPLOYEE ID");
        empID.setBorder(null);
        jPanel1.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 50));

        delete.setBackground(new java.awt.Color(0, 128, 108));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 150, 50));

        update.setBackground(new java.awt.Color(0, 128, 108));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 150, 50));

        add.setBackground(new java.awt.Color(0, 128, 108));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 150, 50));

        clear.setBackground(new java.awt.Color(0, 128, 108));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 150, 50));

        search.setBackground(new java.awt.Color(0, 128, 108));
        search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Emp.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    try {
        String ID = id.getText();

        String sql = "SELECT * FROM Employee WHERE emp_id = ?";
        if (ID.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            // Use PreparedStatement to avoid SQL injection
            ptst = conn.prepareStatement(sql);
            ptst.setString(1, ID);

            rs = ptst.executeQuery();
            
            if (rs.next()) {
                name.setText(rs.getString(2));
                dob.setText(rs.getString(3));
                type.setSelectedItem(rs.getString(4));
                doj.setText(rs.getString(5));
            } else {
                JOptionPane.showMessageDialog(null, "No record found :(");
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_searchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{

            String sql= "insert into Employee values(?,?,?,?,?)";
            PreparedStatement ptst=conn.prepareCall(sql);
            if (id.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter employee ID.","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (name.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter name.","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            
            if (dob.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter date of birth.","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (doj.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter experience.","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (type.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select gender.","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            else{

                ptst.setString(1,id.getText());
                ptst.setString(2,name.getText());
                ptst.setString(3,dob.getText());
                ptst.setString(4,(String)type.getSelectedItem());
                ptst.setString(5,doj.getText());
                ptst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Added Successfully");
                reset();
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        viewEmployees();
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try {
        String ID = id.getText();
        String n = name.getText();
        String b = dob.getText();
        String t = (String)type.getSelectedItem();
        String j = doj.getText();
        
        String sql = "UPDATE Employee SET name=?, dob=?, eType=?, doj=? WHERE emp_id=?";
        
        if(ID.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                PreparedStatement ptst = conn.prepareStatement(sql);

                if (n.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please enter name.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (b.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please enter date of birth.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (t.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please select type.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (j.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please enter date of joining.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Set parameters
                ptst.setString(1, n);
                ptst.setString(2, b);
                ptst.setString(3, t);
                ptst.setString(4, j);
                ptst.setString(5, ID);

                // Execute update
                ptst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data Updated Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    viewEmployees();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String dEmp = id.getText();
                  try{
                
            Statement st = conn.createStatement();
            String sql ="DELETE from Employee WHERE emp_id="+dEmp;
            PreparedStatement ptst=conn.prepareCall(sql);
                                       if(id.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter employee ID.","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
           else{
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(null,"All details of the employee has been deleted.");
             id.setText("");
                                       }
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null,e);
                  }
                  viewEmployees();
    }//GEN-LAST:event_deleteActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_clearActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField doj;
    private javax.swing.JTextField empDOB;
    private javax.swing.JTextField empExperience;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empType;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
