/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        sales = new javax.swing.JButton();
        purchaseOrder = new javax.swing.JButton();
        refund = new javax.swing.JButton();
        supplier = new javax.swing.JButton();
        pcls = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product.setBackground(new java.awt.Color(0, 128, 108));
        product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        product.setForeground(new java.awt.Color(242, 242, 242));
        product.setText("Product");
        product.setBorder(null);
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 180, 80));

        customer.setBackground(new java.awt.Color(0, 128, 108));
        customer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customer.setForeground(new java.awt.Color(242, 242, 242));
        customer.setText("Customer");
        customer.setBorder(null);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 180, 80));

        Employee.setBackground(new java.awt.Color(0, 128, 108));
        Employee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Employee.setForeground(new java.awt.Color(242, 242, 242));
        Employee.setText("Employee");
        Employee.setBorder(null);
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 180, 80));

        sales.setBackground(new java.awt.Color(0, 128, 108));
        sales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sales.setForeground(new java.awt.Color(242, 242, 242));
        sales.setText("Sales");
        sales.setBorder(null);
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        getContentPane().add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 180, 80));

        purchaseOrder.setBackground(new java.awt.Color(0, 128, 108));
        purchaseOrder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        purchaseOrder.setForeground(new java.awt.Color(242, 242, 242));
        purchaseOrder.setText("Purchase Order");
        purchaseOrder.setBorder(null);
        purchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrderActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 180, 80));

        refund.setBackground(new java.awt.Color(0, 128, 108));
        refund.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refund.setForeground(new java.awt.Color(242, 242, 242));
        refund.setText("Refund");
        refund.setBorder(null);
        refund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundActionPerformed(evt);
            }
        });
        getContentPane().add(refund, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 180, 80));

        supplier.setBackground(new java.awt.Color(0, 128, 108));
        supplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        supplier.setForeground(new java.awt.Color(242, 242, 242));
        supplier.setText("Supplier");
        supplier.setBorder(null);
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });
        getContentPane().add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 180, 80));

        pcls.setBackground(new java.awt.Color(0, 128, 108));
        pcls.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pcls.setForeground(new java.awt.Color(242, 242, 242));
        pcls.setText("PCls");
        pcls.setBorder(null);
        pcls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclsActionPerformed(evt);
            }
        });
        getContentPane().add(pcls, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 180, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 108));
        jLabel2.setText("HOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 150, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        jMenuBar1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuBar1.setForeground(new java.awt.Color(0, 128, 108));

        jMenu1.setBackground(new java.awt.Color(210, 227, 195));
        jMenu1.setForeground(new java.awt.Color(0, 128, 108));
        jMenu1.setText("Logout");

        jMenuItem1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuItem1.setForeground(new java.awt.Color(0, 128, 108));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logouticon.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new product().setVisible(true);
    }//GEN-LAST:event_productActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new customer().setVisible(true);
    }//GEN-LAST:event_customerActionPerformed

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new Employee().setVisible(true);
    }//GEN-LAST:event_EmployeeActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new sales().setVisible(true);
    }//GEN-LAST:event_salesActionPerformed

    private void purchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrderActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new PurchaseOrder().setVisible(true);
    }//GEN-LAST:event_purchaseOrderActionPerformed

    private void refundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new cust_phistory().setVisible(true);
    }//GEN-LAST:event_refundActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new supplier().setVisible(true);
    }//GEN-LAST:event_supplierActionPerformed

    private void pclsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclsActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new pcls().setVisible(true);
    }//GEN-LAST:event_pclsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //TODO add your handling code here:
        setVisible(false);
        login obj = new login();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Employee;
    private javax.swing.JButton customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton pcls;
    private javax.swing.JButton product;
    private javax.swing.JButton purchaseOrder;
    private javax.swing.JButton refund;
    private javax.swing.JButton sales;
    private javax.swing.JButton supplier;
    // End of variables declaration//GEN-END:variables
}
