
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.title.TextTitle;
import java.awt.Color;
import java.text.NumberFormat;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PieLabelLinkStyle;
import org.jfree.chart.plot.PieLabelLinkStyle;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class product_chart extends javax.swing.JFrame {

    /**
     * Creates new form product_chart
     */
    Connection conn = null;
    public product_chart() {
        initComponents();
        conn = databaseconnection.connection();
        Map<String, Integer> productData = fetchDataFromDatabase();
        createPieChart(productData);
    }
    private Map<String, Integer> fetchDataFromDatabase() {
      Map<String, Integer> productData = new HashMap<>();

        try {
        String sql = "SELECT prod_group, COUNT(*) AS count FROM product GROUP BY prod_group";
        try (PreparedStatement preparedStatement = conn.prepareStatement(sql);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            while (resultSet.next()) {
                String group = resultSet.getString("prod_group");
                int count = resultSet.getInt("count");
                productData.put(group, count);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return productData;
    }
 

private void createPieChart(Map<String, Integer> productData) {
    DefaultPieDataset dataset = new DefaultPieDataset();
    for (Map.Entry<String, Integer> entry : productData.entrySet()) {
        dataset.setValue(entry.getKey(), entry.getValue());
    }

    JFreeChart chart = ChartFactory.createPieChart(
            "Product Distribution by Group",
            dataset,
            true,
            true,
            false);
    
     // Customize the title color using RGB values
    TextTitle title = chart.getTitle();
    title.setPaint(new Color(0,128,108)); 

    // Customize the background color of the pie chart using RGB values
    PiePlot plot = (PiePlot) chart.getPlot();
    plot.setBackgroundPaint(new Color(210,227,195)); 

    // Customize the PiePlot colors using RGB values
    plot.setSectionPaint("Food", new Color(223,137,109));      
    plot.setSectionPaint("Non-Food", new Color(243,196,48));  
    plot.setSectionPaint("Textile", new Color(183,86,51));   

    // Display the percentage of each group on the chart
    plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0} = {2}", NumberFormat.getPercentInstance(), NumberFormat.getPercentInstance()));

    // Show percentage in the legend
    plot.setLegendLabelGenerator(new StandardPieSectionLabelGenerator("{0} = {2}"));

    // Set the label link style
    plot.setLabelLinkStyle(PieLabelLinkStyle.STANDARD);

    // Adjust other appearance settings as needed
    plot.setShadowPaint(new Color(128, 128, 128)); // Gray color as an example for shadow
    plot.setExplodePercent("Food", 0.10); // Explode a section (e.g., 'Food')

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));

    jPanel1.add(chartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    jPanel1.revalidate();
    jPanel1.repaint();
    
}






    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(210, 227, 195));

        jPanel1.setBackground(new java.awt.Color(210, 227, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 128, 108));
        jButton2.setForeground(new java.awt.Color(210, 227, 195));
        jButton2.setText("BACK");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        product obj = new product();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
