/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class refund extends javax.swing.JFrame {

    /**
     * Creates new form refund
     */
    Connection conn = null;
    DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
    public refund() {
        initComponents();
        conn = databaseconnection.connection();
        headerRenderer.setBackground(new java.awt.Color(0, 128, 108));  // Set the background color
        headerRenderer.setForeground(new java.awt.Color(210, 227, 195));  // Set the text color

        // Apply the custom renderer to the JTableHeader
        jTable1.getTableHeader().setDefaultRenderer(headerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 240, 40));

        jTable1.setBackground(new java.awt.Color(210, 227, 195));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Poduct Name", "Price", "Quantity", "Total Price"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(178, 75, 130));
        jTable1.setSelectionForeground(new java.awt.Color(43, 75, 130));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 980, 290));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 170, 40));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 150, 40));

        jButton1.setBackground(new java.awt.Color(0, 128, 108));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REFUND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 140, 40));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 230, 40));

        jButton3.setBackground(new java.awt.Color(0, 128, 108));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 110, 40));

        jButton2.setBackground(new java.awt.Color(0, 128, 108));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VIEW BILL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zainab\\Desktop\\SEMESTER 3\\Database Systems\\Lab\\project\\GMS\\src\\refund.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 790));

        jMenuBar1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuBar1.setForeground(new java.awt.Color(0, 128, 108));

        jMenu1.setBackground(new java.awt.Color(210, 227, 195));
        jMenu1.setForeground(new java.awt.Color(0, 128, 108));
        jMenu1.setText("Home");

        jMenuItem1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuItem1.setForeground(new java.awt.Color(0, 128, 108));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeicon.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String transno = jTextField3.getText();
        try{
            String sql ="select * from sales_child WHERE Transno ='"+transno+"'";
            PreparedStatement ptst=conn.prepareCall(sql);
            ResultSet rs= ptst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);
            if(!rs.next()||jTextField3.getText().equals("")){
             JOptionPane.showMessageDialog(null, "INVALID TRANSACTION NO");
            }else{
            do{
            String sql1 ="select P.prod_name from product as P JOIN sales_child as S on P.prod_id = "+rs.getString("prod_id");
            PreparedStatement ptst1=conn.prepareCall(sql1);
            ResultSet rs1= ptst1.executeQuery();
            if(rs1.next()){
               Object o[]={rs.getString("prod_id"),rs1.getString("prod_name"),rs.getString("rate"),rs.getString("quantity"),rs.getString("prod_amount")};
               tm.addRow(o);
            }
            }while(rs.next());
        }

        }
        catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
     int set_refundno(){
                  int no=0;
                try {
                String query = "SELECT TOP 1 refund_no FROM refund ORDER BY refund_no DESC ";
                PreparedStatement preparedStatement = conn.prepareStatement(query);
                ResultSet resultSet = preparedStatement.executeQuery();

                if(resultSet.next()){
                no = resultSet.getInt("refund_no")+1;
                }
                else{
                no=0;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
                return no;
    }
     
     void reset(){
     DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
     tm.setRowCount(0);
     jTextField1.setText("");
     jTextField4.setText("");
     jTextField3.setText("");
     jTextField2.setText("");
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if("".equals(jTextField1.getText())||"".equals(jTextField4.getText())||"".equals(jTextField3.getText())||"".equals(jTextField2.getText())){
            JOptionPane.showMessageDialog(null, "ENTER COMPLETE INFORMATION");
            }
        else{
        int prod_id = Integer.parseInt(jTextField1.getText());     
        int quantity = Integer.parseInt(jTextField4.getText()); 
        int transno = Integer.parseInt(jTextField3.getText());
        int refund_id = Integer.parseInt(jTextField2.getText());
        try {
            String sql1 ="select rate,quantity from sales_child WHERE Transno ='"+transno+"' AND prod_id ='"+prod_id+"'";
            PreparedStatement ptst1=conn.prepareCall(sql1);
            ResultSet rs= ptst1.executeQuery();
                 // TODO add your handling code here:
                 String sql= "insert into refund values(?,?,?,?,?,?,?)";
                 PreparedStatement ptst=conn.prepareCall(sql);
                 java.sql.Date sqlDate = java.sql.Date.valueOf(LocalDate.now());
                 ptst.setInt(1,set_refundno());
                 ptst.setInt(2,prod_id);
                 ptst.setInt(3,quantity);
                 if(rs.next()){
                     if(rs.getInt("quantity")<quantity){
                      JOptionPane.showMessageDialog(null, "INVALID COMMAND");
                     }
                     else{
                       ptst.setDouble(4,rs.getDouble("rate"));
                     }
                 }
                 else{
                 JOptionPane.showMessageDialog(null, "PRODUCT NOT FOUND");
                 }
                 ptst.setDate(5,sqlDate);
                 ptst.setDouble(6,refund_id);
                 ptst.setDouble(7,transno);
                 ptst.executeUpdate();
                 JOptionPane.showMessageDialog(null, "REFUNDED");
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, ex);
             }
        set_refundno();
        reset();
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //TODO add your handling code here:
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       new cust_phistory().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new refund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
