/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.lang.System.Logger.Level;
import java.sql.*;
import java.util.function.Supplier;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class supplier extends javax.swing.JFrame {

    //Statement st;
    Connection con = null;
    ResultSet rs;
    PreparedStatement pst;
    public void reset(){
            s_id.setText("");
            factory_name.setText("");
            date.setText("");
            focal_person.setText("");
            address.setText("");
            bank.setText("");   
            contact.setText("");
            branch.setText("");
            account.setText("");
            type.setSelectedItem("");
            status.setSelectedItem("");
    }
    public supplier() {
        super("supplier");
        try {
            initComponents();
            con = databaseconnection.connection();
            
            
            connect();
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }
    public void connect() throws ClassNotFoundException, SQLException{
        
        pst=con.prepareStatement("Select * from supplier");
        //Statement st= con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        rs=pst.executeQuery();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        s_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        factory_name = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        focal_person = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        bank = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        account = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chart = new javax.swing.JButton();
        new_supplier = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        delete.setBackground(new java.awt.Color(0, 128, 108));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(480, 610, 120, 30);

        search.setBackground(new java.awt.Color(0, 128, 108));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(350, 670, 120, 30);

        edit.setBackground(new java.awt.Color(0, 128, 108));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.setBorder(null);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(630, 610, 130, 30);

        type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manufacturer", "wholesaler" }));
        jPanel1.add(type);
        type.setBounds(290, 490, 160, 29);

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "approved", "critical" }));
        jPanel1.add(status);
        status.setBounds(290, 530, 150, 29);

        s_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_idActionPerformed(evt);
            }
        });
        jPanel1.add(s_id);
        s_id.setBounds(290, 130, 120, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 128, 108));
        jLabel1.setText("Supplier ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 130, 90, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 128, 108));
        jLabel10.setText("Type:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(180, 490, 43, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 128, 108));
        jLabel11.setText("Status:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 530, 60, 20);

        factory_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        factory_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factory_nameActionPerformed(evt);
            }
        });
        jPanel1.add(factory_name);
        factory_name.setBounds(290, 170, 240, 30);

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(290, 210, 243, 30);

        focal_person.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        focal_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                focal_personActionPerformed(evt);
            }
        });
        jPanel1.add(focal_person);
        focal_person.setBounds(290, 250, 243, 30);

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(290, 290, 243, 30);

        bank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(bank);
        bank.setBounds(290, 330, 170, 30);

        branch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(branch);
        branch.setBounds(290, 370, 243, 30);

        account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        jPanel1.add(account);
        account.setBounds(290, 410, 243, 30);

        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(contact);
        contact.setBounds(290, 450, 160, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 108));
        jLabel2.setText("Factory Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 170, 100, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 108));
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 210, 37, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 108));
        jLabel4.setText("Focal Person:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 250, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 108));
        jLabel5.setText("Address:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 290, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 128, 108));
        jLabel6.setText("Bank:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 330, 46, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 128, 108));
        jLabel7.setText("Branch:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 370, 59, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 128, 108));
        jLabel8.setText("Account No.:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 410, 90, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 128, 108));
        jLabel9.setText("Contact No.:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(180, 450, 90, 20);

        chart.setBackground(new java.awt.Color(0, 128, 108));
        chart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chart.setForeground(new java.awt.Color(255, 255, 255));
        chart.setText("Stats");
        chart.setBorder(null);
        chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartActionPerformed(evt);
            }
        });
        jPanel1.add(chart);
        chart.setBounds(510, 670, 120, 30);

        new_supplier.setBackground(new java.awt.Color(0, 128, 108));
        new_supplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        new_supplier.setForeground(new java.awt.Color(255, 255, 255));
        new_supplier.setText("New");
        new_supplier.setBorder(null);
        new_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_supplierActionPerformed(evt);
            }
        });
        jPanel1.add(new_supplier);
        new_supplier.setBounds(170, 610, 120, 30);

        save.setBackground(new java.awt.Color(0, 128, 108));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setBorder(null);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(320, 610, 130, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supplier.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1120, 790);

        jMenuBar1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuBar1.setForeground(new java.awt.Color(0, 128, 108));

        jMenu1.setBackground(new java.awt.Color(210, 227, 195));
        jMenu1.setForeground(new java.awt.Color(0, 128, 108));
        jMenu1.setText("Home");

        jMenuItem1.setBackground(new java.awt.Color(210, 227, 195));
        jMenuItem1.setForeground(new java.awt.Color(0, 128, 108));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeicon.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void factory_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factory_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_factory_nameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void focal_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focal_personActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_focal_personActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountActionPerformed

    private void new_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_supplierActionPerformed
        reset();
    }//GEN-LAST:event_new_supplierActionPerformed
// Method to check if a supplier with the given ID already exists
private boolean isSupplierIdExists(int supplierId) {

        try {
            pst = con.prepareStatement("SELECT * FROM supplier WHERE s_id = ?");
            pst.setInt(1, supplierId);
            ResultSet rs = pst.executeQuery();
            return rs.next();  // Returns true if a record is found
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            return false;
        }
}
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    int supplierId = Integer.parseInt(s_id.getText());

    // Check if the supplierId already exists in the 'supplier' table
    if (isSupplierIdExists(supplierId)) {
        JOptionPane.showMessageDialog(this, "Supplier with ID " + supplierId + " already exists.", "Duplicate Entry", JOptionPane.ERROR_MESSAGE);
        // Optionally, you can clear the supplier_id field or take other corrective actions
        s_id.setText("");
        return;  // Exit the method to avoid further processing
    }

    try {
        pst = con.prepareStatement("INSERT INTO supplier(s_id,factory_name,focal_person,s_date,address,bank,branch,account_no,contact,s_type,s_status) VALUES (?, ?, ?,?,?,?,?,?,?,?,?)");
        pst.setInt(1, supplierId);
        pst.setString(2,factory_name.getText());
        pst.setString(3,focal_person.getText());
        try {
            pst.setDate(4, java.sql.Date.valueOf(date.getText()));  // Assuming date is in the format "yyyy-MM-dd"
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the date in the format yyyy-MM-dd.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            // Optionally, you can clear the date field or take other corrective actions
            date.setText("");
            return;  // Exit the method to avoid further processing
        }
        pst.setString(5,address.getText());
        pst.setString(6,bank.getText());
        pst.setString(7,branch.getText());
        pst.setString(8, account.getText());
        pst.setString(9,contact.getText());
        pst.setString(10, type.getSelectedItem().toString());
        pst.setString(11, status.getSelectedItem().toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Success");

        // Your existing code for resetting fields
        reset();
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid supplier ID. Please enter a valid integer.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        // Optionally, you can clear the supplier_id field or take other corrective actions
        s_id.setText("");
    }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            pst=con.prepareStatement("delete from supplier where factory_name=?");
            pst.setString(1,factory_name.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"success");
            
            reset();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try {
        // TODO add your handling code here:
        String typeValue = (String) type.getSelectedItem();
        String statusValue = (String) status.getSelectedItem();

        // Check if values are not null before setting them in the prepared statement
        if (typeValue != null && statusValue != null) {
            pst = con.prepareStatement("UPDATE supplier SET factory_name=?,s_date=?,focal_person=?,address=?,bank=?,branch=?,account_no=?,contact=?,s_type=?,s_status=? WHERE s_id=?");
            pst.setString(1, factory_name.getText());
            try {
                pst.setDate(2, java.sql.Date.valueOf(date.getText()));  // Assuming date is in the format "yyyy-MM-dd"
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the date in the format yyyy-MM-dd.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                // Optionally, you can clear the date field or take other corrective actions
                date.setText("");
                return;  // Exit the method to avoid further processing
            }
            pst.setString(3, focal_person.getText());
            pst.setString(4, address.getText());
            pst.setString(5, bank.getText());
            pst.setString(6, branch.getText());
            pst.setString(7, account.getText());
            pst.setString(8, contact.getText());
            pst.setString(9, typeValue);
            pst.setString(10, statusValue);
            pst.setString(11, s_id.getText());  // This should be the last parameter

            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Update successful");
        } else {
            // Handle the case where one or both values are null
            // You may want to provide default values or handle it according to your application logic
            // For example:
            JOptionPane.showMessageDialog(this, "Type or Status is null");
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_editActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            String s=JOptionPane.showInputDialog(this,"Enter name for search:");
            pst=con.prepareStatement("select * from supplier where factory_name=?");
            pst.setString(1,s);
            rs= pst.executeQuery();
            if (rs.next()){
                s_id.setText(rs.getString(1));
                factory_name.setText(rs.getString(2));
                date.setText(rs.getString(4));
                focal_person.setText(rs.getString(3));
                address.setText(rs.getString(5));
                bank.setText(rs.getString(6));
                branch.setText(rs.getString(7));
                account.setText(rs.getString(8));
                contact.setText(rs.getString(9));
                type.setSelectedItem(rs.getString(10));
                status.setSelectedItem(rs.getString(11));               
            }
            else{
                JOptionPane.showMessageDialog(null, "No record found :(");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_searchActionPerformed

    private void s_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_idActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //TODO add your handling code here:
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        supplier_chart obj = new supplier_chart();
        obj.setVisible(true);
    }//GEN-LAST:event_chartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new supplier().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField address;
    private javax.swing.JTextField bank;
    private javax.swing.JTextField branch;
    private javax.swing.JButton chart;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField factory_name;
    private javax.swing.JTextField focal_person;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton new_supplier;
    private javax.swing.JTextField s_id;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
