/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdatePO extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePO
     */
    Connection conn=null;
    
    public UpdatePO() {
        super("UpdatePO");
        initComponents();
        conn=databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        status = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        orderID = new javax.swing.JTextField();
        OrderID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setBackground(new java.awt.Color(210, 227, 195));
        status.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(0, 128, 108));
        status.setText("STATUS");
        status.setBorder(null);
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 180, 50));

        Status.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Complete", "Cancelled" }));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 370, 40));

        save.setBackground(new java.awt.Color(0, 128, 108));
        save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setBorder(null);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, 180, 50));

        cancel.setBackground(new java.awt.Color(0, 128, 108));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("BACK");
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, 180, 50));

        orderID.setBackground(new java.awt.Color(210, 227, 195));
        orderID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        orderID.setForeground(new java.awt.Color(0, 128, 108));
        orderID.setText("ORDER ID");
        orderID.setBorder(null);
        jPanel1.add(orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 180, 50));

        OrderID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatePO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
         String orderStatus = (String) Status.getSelectedItem();
         String id = OrderID.getText();
        
            String sql="Update PurchaseOrder SET orderStatus='"+orderStatus+"'WHERE orderNo='"+id+"'";
            if(id.equals("")){ 
             JOptionPane.showMessageDialog( this, "Please enter order ID.","Error", JOptionPane.ERROR_MESSAGE);
                return;}
            else{
                 PreparedStatement ptst=conn.prepareCall(sql);
                 ptst.execute();
                 JOptionPane.showMessageDialog(null, "Data Successfully Updated");
            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        PurchaseOrder obj = new PurchaseOrder();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrderID;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderID;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
